### PR TITLE
Update indirect deps

### PR DESCRIPTION
**Pull request by Boojapho**
- Updated go.mod to 1.17 format
- Updated dependencies in go.mod / go.sum using `go get -u -t` and `go mod tidy`
- Bumped version to 1.4.1

> Verified `go test` with go v1.17.6

### CODE REVIEW

**Comment by Boojapho** [comment]
Related to #29

**Comment by jcassee** [comment]
Hi @Boojapho, thanks for this change. It seems `go mod tidy` is generating an error in the build pipeline. From scanning the docs it seems to need `-go=1.17` or `-compat=1.17`. I haven't looked into it myself. Could you take a look at what is required here?

Otherwise looks like a clean change. Great to see you took care of the documentation too.

**Comment by Boojapho** [comment]
@jcassee I looked into it and the problem is that I needed to update the pipeline to build with Go 1.17.   I had already updated `docs/argocd.md`.  I only replaced `1.4.0` with `1.4.1`.  Did I miss something else in there?

**Comment by jcassee** [comment]
You are right! I totally missed your change to `docs/argocd.md`.

I am merging your change. Thanks for contributing. The new version should automatically be released as version 1.4.1 once I tag it.

**Pull request merged**
